<?php
/**
 * Client Service Dependency Injector
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2013 Amy Stephen. All rights reserved.
 *
 */
namespace Molajo\Tests;

use Molajo\Http\Client\Client;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-17 at 11:54:00.
 */
class ClientTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AbstractHttp
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $_SERVER['HTTP_CLIENT_IP']        = '127.0.0.1';
        $_SERVER['REMOTE_HOST']           = 'xyz';
        $_SERVER['HTTP_X_REQUESTED_WITH'] = 'xmlhttprequest';
        $_SERVER['HTTP_HOST']             = 0; //not cli
        $_SERVER['HTTP_USER_AGENT']       = 'macintosh|mac os x firefox';

        $this->object = new Client();
    }

    /**
     * Get the current value (or default) of the specified key
     *
     * @covers Molajo\Http\Client\Client::get
     */
    public function testGet()
    {
        $this->assertEquals('127.0.0.1', $this->object->get('remote_address'));
        $this->assertEquals('xyz', $this->object->get('remote_host'));
        $this->assertEquals('1', $this->object->get('ajax'));
        $this->assertEquals('firefox', $this->object->get('browser'));
        $this->assertEquals('', $this->object->get('browser_version'));
        $this->assertEquals('macintosh|mac os x firefox', $this->object->get('user_agent'));
        $this->assertEquals('1', $this->object->get('desktop'));
        $this->assertEquals('mac', $this->object->get('platform'));
        $this->assertEquals('0', $this->object->get('is_bot'));
        $this->assertEquals('0', $this->object->get('is_cli'));
        $this->assertEquals('', $this->object->get('bot'));
        $this->assertEquals('0', $this->object->get('is_mobile'));
        $this->assertEquals('', $this->object->get('mobile_device'));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
